### ISSUE TITLE
Make it more readable in wheather_api.js

### ISSUE THREAD

**Issue by TWcamel** [pingdori/YJSVD-team#6]
in `wheather_api.js`

1. `get_24h_precipitation_in_Municipality()`
2. `get_3h_precipitation_in_Municipality()`
3. `get_10m_precipitation_in_Municipality()`

這三段 function 看起來好像可以寫成同一段ＸＤ
如果評估後不行的話請幫我 close ， 感恩

-------------------

Update: ebhancement here: PR #11

**Comment by Yintc123** [comment]
聽你說完，我也覺得可以欸!這想法超好的，立刻試試看!謝謝!
